### ISSUE TITLE
Installation of Apache Pig 

### ISSUE THREAD

**Issue by Deepthi1003** [nikithakethireddy1996/apache_pig#3]

**Comment by nikithakethireddy1996** [comment]
Installed pig using the instructions provided in read me and verified it using powershell.

**Comment by Deepakmalempati** [comment]
installation completed

**Comment by Deepthi1003** [comment]
Installation of Apache Pig has been completed successfully with the help of instructions provided in the README.md file and didn't encounter any issues due to the clear description of step-by-step procedure.

**Comment by sushma95** [comment]
Successfully installed.
