### ISSUE TITLE
Proof of installation of Pig in every team members desktop

### ISSUE THREAD

**Issue by nikithakethireddy1996** [nikithakethireddy1996/apache_pig#4]

**Comment by nikithakethireddy1996** [comment]
![Capture2](https://user-images.githubusercontent.com/54380887/82773590-0a6c0600-9e08-11ea-8ddd-36fd4042f80d.PNG)
Submitted the screenshot of my installation

**Comment by Deepakmalempati** [comment]
![Screenshot (170)](https://user-images.githubusercontent.com/54385574/82771538-03da9000-9e02-11ea-97fc-7c70882593a6.png)
Pig installation proof attached

**Comment by Deepthi1003** [comment]
Proof of Installation of Apache Pig
![Screenshot (35)](https://user-images.githubusercontent.com/54445933/82773875-ccbbad00-9e08-11ea-94a8-7f93ef21621d.png)

**Comment by sushma95** [comment]
![pigversion](https://user-images.githubusercontent.com/54374529/82840965-130d1c80-9e9a-11ea-90ae-b4a3424fff56.PNG)

-- proof of installation.
